### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by camilosampedro**
Thank you for this repository, it is an interesting implementation!

I just took the English translation and translated each of the words to Spanish, checking each of them individually.

Let me know if there is anything else I should do to include this translation

### CODE REVIEW

**Comment by alenros** [comment]
@camilosampedro Sorry for the late reply!
Thanks for your contribution, I will check it out and deploy it. (if I don't do this within a day or 2 feel free to remind me)
I will add credits to pointing to your Github user.

**Comment by camilosampedro** [comment]
Hi, thank you!

Let me know if I can be of any help

**Comment by alenros** [comment]
Could you add this to the start of the file?
`words_es = [`

**Comment by alenros** [comment]
could you help me with translating the credits line?
I want it to be something along these lines:
`Translated by: <a href='https://github.com/camilosampedro'>camilosampedro</a>`

**Comment by camilosampedro** [comment]
@alenros Sorry for the wait, I applied the changes and resolved the conflicts 👍

**Comment by camilosampedro** [comment]
I just applied some extra small fixes on the i18n es file. Including formatting the file

**Review by alenros — APPROVED** [review]

**Pull request merged**
