### PR TITLE
Improve translations and formatting, add French translation

### PR DESCRIPTION
**Pull request by fbarbe00**
The translations seemed to be outdated, I have updated and improved the ones in German, Italian, and Spanish. I also added French translations, translated all English words to French. Note: some translations might not be relevant in French.

### CODE REVIEW

**Comment by fbarbe00** [comment]
Thanks a lot for coding this btw, it's a lot of fun! As you probably know, fake-artist.herokuapp.com no longer works, but it should be fairly easy to set it up on github actions (?)

**Comment by alenros** [comment]
Thanks for helping out with the translations!
If you know how to set it up in GH actions that would be great!
I succeeded in running the application in docker, but since it packs Meteor it requires more than 2Gb RAM, which doesn't fit most small cloud VM instances.

**Comment by fbarbe00** [comment]
Could you merge this PR first so I can experiment with GH actions on my branch and open a new PR if it works?

**Comment by fbarbe00** [comment]
I tested on another branch on my fork (now deleted), but could not find a simple way to make it work :(

**Comment by fbarbe00** [comment]
Hi, are there any plans to merge this?

**Comment by alenros** [comment]
I will, but it will take me a day or so.

**Comment by fbarbe00** [comment]
Awesome, thanks a lot for your work!

**Comment by fbarbe00** [comment]
Just a little heads up ;)! This also touches #47 btw! Design isn't the prettiest tho

**Pull request merged**
